# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.activity_zone_sample import ActivityZoneSample  # noqa: F401,E501
from swagger_server import util


class ActivityZoneSamples(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, interval: int=None, samples: List[ActivityZoneSample]=None):  # noqa: E501
        """ActivityZoneSamples - a model defined in Swagger

        :param _date: The _date of this ActivityZoneSamples.  # noqa: E501
        :type _date: str
        :param interval: The interval of this ActivityZoneSamples.  # noqa: E501
        :type interval: int
        :param samples: The samples of this ActivityZoneSamples.  # noqa: E501
        :type samples: List[ActivityZoneSample]
        """
        self.swagger_types = {
            '_date': str,
            'interval': int,
            'samples': List[ActivityZoneSample]
        }

        self.attribute_map = {
            '_date': 'date',
            'interval': 'interval',
            'samples': 'samples'
        }
        self.__date = _date
        self._interval = interval
        self._samples = samples

    @classmethod
    def from_dict(cls, dikt) -> 'ActivityZoneSamples':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The activity-zone-samples of this ActivityZoneSamples.  # noqa: E501
        :rtype: ActivityZoneSamples
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this ActivityZoneSamples.

        Activity zone sample date  # noqa: E501

        :return: The _date of this ActivityZoneSamples.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this ActivityZoneSamples.

        Activity zone sample date  # noqa: E501

        :param _date: The _date of this ActivityZoneSamples.
        :type _date: str
        """

        self.__date = _date

    @property
    def interval(self) -> int:
        """Gets the interval of this ActivityZoneSamples.

        Sample interval in minutes.  # noqa: E501

        :return: The interval of this ActivityZoneSamples.
        :rtype: int
        """
        return self._interval

    @interval.setter
    def interval(self, interval: int):
        """Sets the interval of this ActivityZoneSamples.

        Sample interval in minutes.  # noqa: E501

        :param interval: The interval of this ActivityZoneSamples.
        :type interval: int
        """

        self._interval = interval

    @property
    def samples(self) -> List[ActivityZoneSample]:
        """Gets the samples of this ActivityZoneSamples.

        List of individual zone sample objects.  # noqa: E501

        :return: The samples of this ActivityZoneSamples.
        :rtype: List[ActivityZoneSample]
        """
        return self._samples

    @samples.setter
    def samples(self, samples: List[ActivityZoneSample]):
        """Sets the samples of this ActivityZoneSamples.

        List of individual zone sample objects.  # noqa: E501

        :param samples: The samples of this ActivityZoneSamples.
        :type samples: List[ActivityZoneSample]
        """

        self._samples = samples
