# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.activity_step_sample import ActivityStepSample  # noqa: F401,E501
from swagger_server import util


class ActivityStepSamples(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, interval: int=None, samples: List[ActivityStepSample]=None):  # noqa: E501
        """ActivityStepSamples - a model defined in Swagger

        :param _date: The _date of this ActivityStepSamples.  # noqa: E501
        :type _date: str
        :param interval: The interval of this ActivityStepSamples.  # noqa: E501
        :type interval: int
        :param samples: The samples of this ActivityStepSamples.  # noqa: E501
        :type samples: List[ActivityStepSample]
        """
        self.swagger_types = {
            '_date': str,
            'interval': int,
            'samples': List[ActivityStepSample]
        }

        self.attribute_map = {
            '_date': 'date',
            'interval': 'interval',
            'samples': 'samples'
        }
        self.__date = _date
        self._interval = interval
        self._samples = samples

    @classmethod
    def from_dict(cls, dikt) -> 'ActivityStepSamples':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The activity-step-samples of this ActivityStepSamples.  # noqa: E501
        :rtype: ActivityStepSamples
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this ActivityStepSamples.

        Activity step sample date  # noqa: E501

        :return: The _date of this ActivityStepSamples.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this ActivityStepSamples.

        Activity step sample date  # noqa: E501

        :param _date: The _date of this ActivityStepSamples.
        :type _date: str
        """

        self.__date = _date

    @property
    def interval(self) -> int:
        """Gets the interval of this ActivityStepSamples.

        Sample interval in minutes.  # noqa: E501

        :return: The interval of this ActivityStepSamples.
        :rtype: int
        """
        return self._interval

    @interval.setter
    def interval(self, interval: int):
        """Sets the interval of this ActivityStepSamples.

        Sample interval in minutes.  # noqa: E501

        :param interval: The interval of this ActivityStepSamples.
        :type interval: int
        """

        self._interval = interval

    @property
    def samples(self) -> List[ActivityStepSample]:
        """Gets the samples of this ActivityStepSamples.

        List of individual step sample objects.  # noqa: E501

        :return: The samples of this ActivityStepSamples.
        :rtype: List[ActivityStepSample]
        """
        return self._samples

    @samples.setter
    def samples(self, samples: List[ActivityStepSample]):
        """Sets the samples of this ActivityStepSamples.

        List of individual step sample objects.  # noqa: E501

        :param samples: The samples of this ActivityStepSamples.
        :type samples: List[ActivityStepSample]
        """

        self._samples = samples
