# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ActivityLog(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, activity_log: List[str]=None):  # noqa: E501
        """ActivityLog - a model defined in Swagger

        :param activity_log: The activity_log of this ActivityLog.  # noqa: E501
        :type activity_log: List[str]
        """
        self.swagger_types = {
            'activity_log': List[str]
        }

        self.attribute_map = {
            'activity_log': 'activity-log'
        }
        self._activity_log = activity_log

    @classmethod
    def from_dict(cls, dikt) -> 'ActivityLog':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The activity-log of this ActivityLog.  # noqa: E501
        :rtype: ActivityLog
        """
        return util.deserialize_model(dikt, cls)

    @property
    def activity_log(self) -> List[str]:
        """Gets the activity_log of this ActivityLog.

        Absolute links to individual activity summaries within the transaction  # noqa: E501

        :return: The activity_log of this ActivityLog.
        :rtype: List[str]
        """
        return self._activity_log

    @activity_log.setter
    def activity_log(self, activity_log: List[str]):
        """Sets the activity_log of this ActivityLog.

        Absolute links to individual activity summaries within the transaction  # noqa: E501

        :param activity_log: The activity_log of this ActivityLog.
        :type activity_log: List[str]
        """

        self._activity_log = activity_log
