# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AvailableSleep(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: date=None, start_time: datetime=None, end_time: datetime=None):  # noqa: E501
        """AvailableSleep - a model defined in Swagger

        :param _date: The _date of this AvailableSleep.  # noqa: E501
        :type _date: date
        :param start_time: The start_time of this AvailableSleep.  # noqa: E501
        :type start_time: datetime
        :param end_time: The end_time of this AvailableSleep.  # noqa: E501
        :type end_time: datetime
        """
        self.swagger_types = {
            '_date': date,
            'start_time': datetime,
            'end_time': datetime
        }

        self.attribute_map = {
            '_date': 'date',
            'start_time': 'start_time',
            'end_time': 'end_time'
        }
        self.__date = _date
        self._start_time = start_time
        self._end_time = end_time

    @classmethod
    def from_dict(cls, dikt) -> 'AvailableSleep':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The available-sleep of this AvailableSleep.  # noqa: E501
        :rtype: AvailableSleep
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> date:
        """Gets the _date of this AvailableSleep.

        Result date of the sleep  # noqa: E501

        :return: The _date of this AvailableSleep.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this AvailableSleep.

        Result date of the sleep  # noqa: E501

        :param _date: The _date of this AvailableSleep.
        :type _date: date
        """

        self.__date = _date

    @property
    def start_time(self) -> datetime:
        """Gets the start_time of this AvailableSleep.

        Start timestamp of the sleep as ISO-8601 datetime string  # noqa: E501

        :return: The start_time of this AvailableSleep.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: datetime):
        """Sets the start_time of this AvailableSleep.

        Start timestamp of the sleep as ISO-8601 datetime string  # noqa: E501

        :param start_time: The start_time of this AvailableSleep.
        :type start_time: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self) -> datetime:
        """Gets the end_time of this AvailableSleep.

        End timestamp of the sleep as ISO-8601 datetime string  # noqa: E501

        :return: The end_time of this AvailableSleep.
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: datetime):
        """Sets the end_time of this AvailableSleep.

        End timestamp of the sleep as ISO-8601 datetime string  # noqa: E501

        :param end_time: The end_time of this AvailableSleep.
        :type end_time: datetime
        """

        self._end_time = end_time
