# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.available_user_data import AvailableUserData  # noqa: F401,E501
from swagger_server import util


class AvailableUserDatas(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, available_user_data: List[AvailableUserData]=None):  # noqa: E501
        """AvailableUserDatas - a model defined in Swagger

        :param available_user_data: The available_user_data of this AvailableUserDatas.  # noqa: E501
        :type available_user_data: List[AvailableUserData]
        """
        self.swagger_types = {
            'available_user_data': List[AvailableUserData]
        }

        self.attribute_map = {
            'available_user_data': 'available-user-data'
        }
        self._available_user_data = available_user_data

    @classmethod
    def from_dict(cls, dikt) -> 'AvailableUserDatas':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The available-user-datas of this AvailableUserDatas.  # noqa: E501
        :rtype: AvailableUserDatas
        """
        return util.deserialize_model(dikt, cls)

    @property
    def available_user_data(self) -> List[AvailableUserData]:
        """Gets the available_user_data of this AvailableUserDatas.

        List of available user datas.  # noqa: E501

        :return: The available_user_data of this AvailableUserDatas.
        :rtype: List[AvailableUserData]
        """
        return self._available_user_data

    @available_user_data.setter
    def available_user_data(self, available_user_data: List[AvailableUserData]):
        """Sets the available_user_data of this AvailableUserDatas.

        List of available user datas.  # noqa: E501

        :param available_user_data: The available_user_data of this AvailableUserDatas.
        :type available_user_data: List[AvailableUserData]
        """

        self._available_user_data = available_user_data
