# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CardioLoadStatusEnum(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    LOAD_STATUS_NOT_AVAILABLE = "LOAD_STATUS_NOT_AVAILABLE"
    DETRAINING = "DETRAINING"
    MAINTAINING = "MAINTAINING"
    PRODUCTIVE = "PRODUCTIVE"
    OVERREACHING = "OVERREACHING"
    UNRECOGNIZED = "UNRECOGNIZED"
    def __init__(self):  # noqa: E501
        """CardioLoadStatusEnum - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CardioLoadStatusEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cardio-load-status-enum of this CardioLoadStatusEnum.  # noqa: E501
        :rtype: CardioLoadStatusEnum
        """
        return util.deserialize_model(dikt, cls)
