# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CardioLoadLevels(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, very_low: float=None, low: float=None, medium: float=None, high: float=None, very_high: float=None):  # noqa: E501
        """CardioLoadLevels - a model defined in Swagger

        :param very_low: The very_low of this CardioLoadLevels.  # noqa: E501
        :type very_low: float
        :param low: The low of this CardioLoadLevels.  # noqa: E501
        :type low: float
        :param medium: The medium of this CardioLoadLevels.  # noqa: E501
        :type medium: float
        :param high: The high of this CardioLoadLevels.  # noqa: E501
        :type high: float
        :param very_high: The very_high of this CardioLoadLevels.  # noqa: E501
        :type very_high: float
        """
        self.swagger_types = {
            'very_low': float,
            'low': float,
            'medium': float,
            'high': float,
            'very_high': float
        }

        self.attribute_map = {
            'very_low': 'very_low',
            'low': 'low',
            'medium': 'medium',
            'high': 'high',
            'very_high': 'very-high'
        }
        self._very_low = very_low
        self._low = low
        self._medium = medium
        self._high = high
        self._very_high = very_high

    @classmethod
    def from_dict(cls, dikt) -> 'CardioLoadLevels':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cardio-load-levels of this CardioLoadLevels.  # noqa: E501
        :rtype: CardioLoadLevels
        """
        return util.deserialize_model(dikt, cls)

    @property
    def very_low(self) -> float:
        """Gets the very_low of this CardioLoadLevels.


        :return: The very_low of this CardioLoadLevels.
        :rtype: float
        """
        return self._very_low

    @very_low.setter
    def very_low(self, very_low: float):
        """Sets the very_low of this CardioLoadLevels.


        :param very_low: The very_low of this CardioLoadLevels.
        :type very_low: float
        """

        self._very_low = very_low

    @property
    def low(self) -> float:
        """Gets the low of this CardioLoadLevels.


        :return: The low of this CardioLoadLevels.
        :rtype: float
        """
        return self._low

    @low.setter
    def low(self, low: float):
        """Sets the low of this CardioLoadLevels.


        :param low: The low of this CardioLoadLevels.
        :type low: float
        """

        self._low = low

    @property
    def medium(self) -> float:
        """Gets the medium of this CardioLoadLevels.


        :return: The medium of this CardioLoadLevels.
        :rtype: float
        """
        return self._medium

    @medium.setter
    def medium(self, medium: float):
        """Sets the medium of this CardioLoadLevels.


        :param medium: The medium of this CardioLoadLevels.
        :type medium: float
        """

        self._medium = medium

    @property
    def high(self) -> float:
        """Gets the high of this CardioLoadLevels.


        :return: The high of this CardioLoadLevels.
        :rtype: float
        """
        return self._high

    @high.setter
    def high(self, high: float):
        """Sets the high of this CardioLoadLevels.


        :param high: The high of this CardioLoadLevels.
        :type high: float
        """

        self._high = high

    @property
    def very_high(self) -> float:
        """Gets the very_high of this CardioLoadLevels.


        :return: The very_high of this CardioLoadLevels.
        :rtype: float
        """
        return self._very_high

    @very_high.setter
    def very_high(self, very_high: float):
        """Sets the very_high of this CardioLoadLevels.


        :param very_high: The very_high of this CardioLoadLevels.
        :type very_high: float
        """

        self._very_high = very_high
