# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cardio_load import CardioLoad  # noqa: F401,E501
from swagger_server import util


class CardioLoadSchema(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """CardioLoadSchema - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CardioLoadSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cardio-load-schema of this CardioLoadSchema.  # noqa: E501
        :rtype: CardioLoadSchema
        """
        return util.deserialize_model(dikt, cls)
