# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ContinuousheartrateHeartRateSamples(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, heart_rate: int=None, sample_time: date=None):  # noqa: E501
        """ContinuousheartrateHeartRateSamples - a model defined in Swagger

        :param heart_rate: The heart_rate of this ContinuousheartrateHeartRateSamples.  # noqa: E501
        :type heart_rate: int
        :param sample_time: The sample_time of this ContinuousheartrateHeartRateSamples.  # noqa: E501
        :type sample_time: date
        """
        self.swagger_types = {
            'heart_rate': int,
            'sample_time': date
        }

        self.attribute_map = {
            'heart_rate': 'heart_rate',
            'sample_time': 'sample_time'
        }
        self._heart_rate = heart_rate
        self._sample_time = sample_time

    @classmethod
    def from_dict(cls, dikt) -> 'ContinuousheartrateHeartRateSamples':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The continuousheartrate_heart_rate_samples of this ContinuousheartrateHeartRateSamples.  # noqa: E501
        :rtype: ContinuousheartrateHeartRateSamples
        """
        return util.deserialize_model(dikt, cls)

    @property
    def heart_rate(self) -> int:
        """Gets the heart_rate of this ContinuousheartrateHeartRateSamples.

        heart rate rpm  # noqa: E501

        :return: The heart_rate of this ContinuousheartrateHeartRateSamples.
        :rtype: int
        """
        return self._heart_rate

    @heart_rate.setter
    def heart_rate(self, heart_rate: int):
        """Sets the heart_rate of this ContinuousheartrateHeartRateSamples.

        heart rate rpm  # noqa: E501

        :param heart_rate: The heart_rate of this ContinuousheartrateHeartRateSamples.
        :type heart_rate: int
        """

        self._heart_rate = heart_rate

    @property
    def sample_time(self) -> date:
        """Gets the sample_time of this ContinuousheartrateHeartRateSamples.

        Measurement time of heart rate. Device time used for measurement  # noqa: E501

        :return: The sample_time of this ContinuousheartrateHeartRateSamples.
        :rtype: date
        """
        return self._sample_time

    @sample_time.setter
    def sample_time(self, sample_time: date):
        """Sets the sample_time of this ContinuousheartrateHeartRateSamples.

        Measurement time of heart rate. Device time used for measurement  # noqa: E501

        :param sample_time: The sample_time of this ContinuousheartrateHeartRateSamples.
        :type sample_time: date
        """

        self._sample_time = sample_time
