# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.created_webhook_data import CreatedWebhookData  # noqa: F401,E501
from swagger_server import util


class CreatedWebhook(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: CreatedWebhookData=None):  # noqa: E501
        """CreatedWebhook - a model defined in Swagger

        :param data: The data of this CreatedWebhook.  # noqa: E501
        :type data: CreatedWebhookData
        """
        self.swagger_types = {
            'data': CreatedWebhookData
        }

        self.attribute_map = {
            'data': 'data'
        }
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'CreatedWebhook':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The createdWebhook of this CreatedWebhook.  # noqa: E501
        :rtype: CreatedWebhook
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> CreatedWebhookData:
        """Gets the data of this CreatedWebhook.


        :return: The data of this CreatedWebhook.
        :rtype: CreatedWebhookData
        """
        return self._data

    @data.setter
    def data(self, data: CreatedWebhookData):
        """Sets the data of this CreatedWebhook.


        :param data: The data of this CreatedWebhook.
        :type data: CreatedWebhookData
        """

        self._data = data
