# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DurationZone(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, index: int=None, inzone: str=None):  # noqa: E501
        """DurationZone - a model defined in Swagger

        :param index: The index of this DurationZone.  # noqa: E501
        :type index: int
        :param inzone: The inzone of this DurationZone.  # noqa: E501
        :type inzone: str
        """
        self.swagger_types = {
            'index': int,
            'inzone': str
        }

        self.attribute_map = {
            'index': 'index',
            'inzone': 'inzone'
        }
        self._index = index
        self._inzone = inzone

    @classmethod
    def from_dict(cls, dikt) -> 'DurationZone':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DurationZone of this DurationZone.  # noqa: E501
        :rtype: DurationZone
        """
        return util.deserialize_model(dikt, cls)

    @property
    def index(self) -> int:
        """Gets the index of this DurationZone.

        Activity zone index  # noqa: E501

        :return: The index of this DurationZone.
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index: int):
        """Sets the index of this DurationZone.

        Activity zone index  # noqa: E501

        :param index: The index of this DurationZone.
        :type index: int
        """

        self._index = index

    @property
    def inzone(self) -> str:
        """Gets the inzone of this DurationZone.

        Time duration spent in the zone ISO 8601  # noqa: E501

        :return: The inzone of this DurationZone.
        :rtype: str
        """
        return self._inzone

    @inzone.setter
    def inzone(self, inzone: str):
        """Sets the inzone of this DurationZone.

        Time duration spent in the zone ISO 8601  # noqa: E501

        :param inzone: The inzone of this DurationZone.
        :type inzone: str
        """

        self._inzone = inzone
