# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Exercises(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, exercises: List[str]=None):  # noqa: E501
        """Exercises - a model defined in Swagger

        :param exercises: The exercises of this Exercises.  # noqa: E501
        :type exercises: List[str]
        """
        self.swagger_types = {
            'exercises': List[str]
        }

        self.attribute_map = {
            'exercises': 'exercises'
        }
        self._exercises = exercises

    @classmethod
    def from_dict(cls, dikt) -> 'Exercises':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The exercises of this Exercises.  # noqa: E501
        :rtype: Exercises
        """
        return util.deserialize_model(dikt, cls)

    @property
    def exercises(self) -> List[str]:
        """Gets the exercises of this Exercises.

        Absolute links to individual exercises within the transaction  # noqa: E501

        :return: The exercises of this Exercises.
        :rtype: List[str]
        """
        return self._exercises

    @exercises.setter
    def exercises(self, exercises: List[str]):
        """Sets the exercises of this Exercises.

        Absolute links to individual exercises within the transaction  # noqa: E501

        :param exercises: The exercises of this Exercises.
        :type exercises: List[str]
        """

        self._exercises = exercises
