# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.sleep import Sleep  # noqa: F401,E501
from swagger_server import util


class Nights(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nights: List[Sleep]=None):  # noqa: E501
        """Nights - a model defined in Swagger

        :param nights: The nights of this Nights.  # noqa: E501
        :type nights: List[Sleep]
        """
        self.swagger_types = {
            'nights': List[Sleep]
        }

        self.attribute_map = {
            'nights': 'nights'
        }
        self._nights = nights

    @classmethod
    def from_dict(cls, dikt) -> 'Nights':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The nights of this Nights.  # noqa: E501
        :rtype: Nights
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nights(self) -> List[Sleep]:
        """Gets the nights of this Nights.

        List of sleep objects  # noqa: E501

        :return: The nights of this Nights.
        :rtype: List[Sleep]
        """
        return self._nights

    @nights.setter
    def nights(self, nights: List[Sleep]):
        """Sets the nights of this Nights.

        List of sleep objects  # noqa: E501

        :param nights: The nights of this Nights.
        :type nights: List[Sleep]
        """

        self._nights = nights
