# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PhysicalInformations(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, physical_informations: List[str]=None):  # noqa: E501
        """PhysicalInformations - a model defined in Swagger

        :param physical_informations: The physical_informations of this PhysicalInformations.  # noqa: E501
        :type physical_informations: List[str]
        """
        self.swagger_types = {
            'physical_informations': List[str]
        }

        self.attribute_map = {
            'physical_informations': 'physical-informations'
        }
        self._physical_informations = physical_informations

    @classmethod
    def from_dict(cls, dikt) -> 'PhysicalInformations':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The physical-informations of this PhysicalInformations.  # noqa: E501
        :rtype: PhysicalInformations
        """
        return util.deserialize_model(dikt, cls)

    @property
    def physical_informations(self) -> List[str]:
        """Gets the physical_informations of this PhysicalInformations.

        Absolute links to individual physical information within the transaction  # noqa: E501

        :return: The physical_informations of this PhysicalInformations.
        :rtype: List[str]
        """
        return self._physical_informations

    @physical_informations.setter
    def physical_informations(self, physical_informations: List[str]):
        """Sets the physical_informations of this PhysicalInformations.

        Absolute links to individual physical information within the transaction  # noqa: E501

        :param physical_informations: The physical_informations of this PhysicalInformations.
        :type physical_informations: List[str]
        """

        self._physical_informations = physical_informations
