# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.nightly_recharge import NightlyRecharge  # noqa: F401,E501
from swagger_server import util


class Recharges(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, recharges: List[NightlyRecharge]=None):  # noqa: E501
        """Recharges - a model defined in Swagger

        :param recharges: The recharges of this Recharges.  # noqa: E501
        :type recharges: List[NightlyRecharge]
        """
        self.swagger_types = {
            'recharges': List[NightlyRecharge]
        }

        self.attribute_map = {
            'recharges': 'recharges'
        }
        self._recharges = recharges

    @classmethod
    def from_dict(cls, dikt) -> 'Recharges':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The recharges of this Recharges.  # noqa: E501
        :rtype: Recharges
        """
        return util.deserialize_model(dikt, cls)

    @property
    def recharges(self) -> List[NightlyRecharge]:
        """Gets the recharges of this Recharges.

        List of Nightly Recharge objects  # noqa: E501

        :return: The recharges of this Recharges.
        :rtype: List[NightlyRecharge]
        """
        return self._recharges

    @recharges.setter
    def recharges(self, recharges: List[NightlyRecharge]):
        """Sets the recharges of this Recharges.

        List of Nightly Recharge objects  # noqa: E501

        :param recharges: The recharges of this Recharges.
        :type recharges: List[NightlyRecharge]
        """

        self._recharges = recharges
