# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SkinContactChange(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, skin_contact: bool=None, recording_time_delta_milliseconds: int=None):  # noqa: E501
        """SkinContactChange - a model defined in Swagger

        :param skin_contact: The skin_contact of this SkinContactChange.  # noqa: E501
        :type skin_contact: bool
        :param recording_time_delta_milliseconds: The recording_time_delta_milliseconds of this SkinContactChange.  # noqa: E501
        :type recording_time_delta_milliseconds: int
        """
        self.swagger_types = {
            'skin_contact': bool,
            'recording_time_delta_milliseconds': int
        }

        self.attribute_map = {
            'skin_contact': 'skin_contact',
            'recording_time_delta_milliseconds': 'recording_time_delta_milliseconds'
        }
        self._skin_contact = skin_contact
        self._recording_time_delta_milliseconds = recording_time_delta_milliseconds

    @classmethod
    def from_dict(cls, dikt) -> 'SkinContactChange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The skin-contact-change of this SkinContactChange.  # noqa: E501
        :rtype: SkinContactChange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def skin_contact(self) -> bool:
        """Gets the skin_contact of this SkinContactChange.


        :return: The skin_contact of this SkinContactChange.
        :rtype: bool
        """
        return self._skin_contact

    @skin_contact.setter
    def skin_contact(self, skin_contact: bool):
        """Sets the skin_contact of this SkinContactChange.


        :param skin_contact: The skin_contact of this SkinContactChange.
        :type skin_contact: bool
        """

        self._skin_contact = skin_contact

    @property
    def recording_time_delta_milliseconds(self) -> int:
        """Gets the recording_time_delta_milliseconds of this SkinContactChange.


        :return: The recording_time_delta_milliseconds of this SkinContactChange.
        :rtype: int
        """
        return self._recording_time_delta_milliseconds

    @recording_time_delta_milliseconds.setter
    def recording_time_delta_milliseconds(self, recording_time_delta_milliseconds: int):
        """Sets the recording_time_delta_milliseconds of this SkinContactChange.


        :param recording_time_delta_milliseconds: The recording_time_delta_milliseconds of this SkinContactChange.
        :type recording_time_delta_milliseconds: int
        """

        self._recording_time_delta_milliseconds = recording_time_delta_milliseconds
