# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SkinTemperature(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sleep_time_skin_temperature_celsius: float=None, deviation_from_baseline_celsius: float=None, sleep_date: date=None):  # noqa: E501
        """SkinTemperature - a model defined in Swagger

        :param sleep_time_skin_temperature_celsius: The sleep_time_skin_temperature_celsius of this SkinTemperature.  # noqa: E501
        :type sleep_time_skin_temperature_celsius: float
        :param deviation_from_baseline_celsius: The deviation_from_baseline_celsius of this SkinTemperature.  # noqa: E501
        :type deviation_from_baseline_celsius: float
        :param sleep_date: The sleep_date of this SkinTemperature.  # noqa: E501
        :type sleep_date: date
        """
        self.swagger_types = {
            'sleep_time_skin_temperature_celsius': float,
            'deviation_from_baseline_celsius': float,
            'sleep_date': date
        }

        self.attribute_map = {
            'sleep_time_skin_temperature_celsius': 'sleep_time_skin_temperature_celsius',
            'deviation_from_baseline_celsius': 'deviation_from_baseline_celsius',
            'sleep_date': 'sleep_date'
        }
        self._sleep_time_skin_temperature_celsius = sleep_time_skin_temperature_celsius
        self._deviation_from_baseline_celsius = deviation_from_baseline_celsius
        self._sleep_date = sleep_date

    @classmethod
    def from_dict(cls, dikt) -> 'SkinTemperature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The skin-temperature of this SkinTemperature.  # noqa: E501
        :rtype: SkinTemperature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sleep_time_skin_temperature_celsius(self) -> float:
        """Gets the sleep_time_skin_temperature_celsius of this SkinTemperature.


        :return: The sleep_time_skin_temperature_celsius of this SkinTemperature.
        :rtype: float
        """
        return self._sleep_time_skin_temperature_celsius

    @sleep_time_skin_temperature_celsius.setter
    def sleep_time_skin_temperature_celsius(self, sleep_time_skin_temperature_celsius: float):
        """Sets the sleep_time_skin_temperature_celsius of this SkinTemperature.


        :param sleep_time_skin_temperature_celsius: The sleep_time_skin_temperature_celsius of this SkinTemperature.
        :type sleep_time_skin_temperature_celsius: float
        """

        self._sleep_time_skin_temperature_celsius = sleep_time_skin_temperature_celsius

    @property
    def deviation_from_baseline_celsius(self) -> float:
        """Gets the deviation_from_baseline_celsius of this SkinTemperature.


        :return: The deviation_from_baseline_celsius of this SkinTemperature.
        :rtype: float
        """
        return self._deviation_from_baseline_celsius

    @deviation_from_baseline_celsius.setter
    def deviation_from_baseline_celsius(self, deviation_from_baseline_celsius: float):
        """Sets the deviation_from_baseline_celsius of this SkinTemperature.


        :param deviation_from_baseline_celsius: The deviation_from_baseline_celsius of this SkinTemperature.
        :type deviation_from_baseline_celsius: float
        """

        self._deviation_from_baseline_celsius = deviation_from_baseline_celsius

    @property
    def sleep_date(self) -> date:
        """Gets the sleep_date of this SkinTemperature.


        :return: The sleep_date of this SkinTemperature.
        :rtype: date
        """
        return self._sleep_date

    @sleep_date.setter
    def sleep_date(self, sleep_date: date):
        """Sets the sleep_date of this SkinTemperature.


        :param sleep_date: The sleep_date of this SkinTemperature.
        :type sleep_date: date
        """

        self._sleep_date = sleep_date
