# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.skin_contact_change import SkinContactChange  # noqa: F401,E501
from swagger_server import util


class SkinContactPeriod(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, source_device_id: str=None, start_time: datetime=None, end_time: datetime=None, modified_time: datetime=None, skin_contact_changes: List[SkinContactChange]=None):  # noqa: E501
        """SkinContactPeriod - a model defined in Swagger

        :param source_device_id: The source_device_id of this SkinContactPeriod.  # noqa: E501
        :type source_device_id: str
        :param start_time: The start_time of this SkinContactPeriod.  # noqa: E501
        :type start_time: datetime
        :param end_time: The end_time of this SkinContactPeriod.  # noqa: E501
        :type end_time: datetime
        :param modified_time: The modified_time of this SkinContactPeriod.  # noqa: E501
        :type modified_time: datetime
        :param skin_contact_changes: The skin_contact_changes of this SkinContactPeriod.  # noqa: E501
        :type skin_contact_changes: List[SkinContactChange]
        """
        self.swagger_types = {
            'source_device_id': str,
            'start_time': datetime,
            'end_time': datetime,
            'modified_time': datetime,
            'skin_contact_changes': List[SkinContactChange]
        }

        self.attribute_map = {
            'source_device_id': 'source_device_id',
            'start_time': 'start_time',
            'end_time': 'end_time',
            'modified_time': 'modified_time',
            'skin_contact_changes': 'skin_contact_changes'
        }
        self._source_device_id = source_device_id
        self._start_time = start_time
        self._end_time = end_time
        self._modified_time = modified_time
        self._skin_contact_changes = skin_contact_changes

    @classmethod
    def from_dict(cls, dikt) -> 'SkinContactPeriod':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The skin-contact-period of this SkinContactPeriod.  # noqa: E501
        :rtype: SkinContactPeriod
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_device_id(self) -> str:
        """Gets the source_device_id of this SkinContactPeriod.


        :return: The source_device_id of this SkinContactPeriod.
        :rtype: str
        """
        return self._source_device_id

    @source_device_id.setter
    def source_device_id(self, source_device_id: str):
        """Sets the source_device_id of this SkinContactPeriod.


        :param source_device_id: The source_device_id of this SkinContactPeriod.
        :type source_device_id: str
        """

        self._source_device_id = source_device_id

    @property
    def start_time(self) -> datetime:
        """Gets the start_time of this SkinContactPeriod.

        Measurement period start time (UTC)  # noqa: E501

        :return: The start_time of this SkinContactPeriod.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: datetime):
        """Sets the start_time of this SkinContactPeriod.

        Measurement period start time (UTC)  # noqa: E501

        :param start_time: The start_time of this SkinContactPeriod.
        :type start_time: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self) -> datetime:
        """Gets the end_time of this SkinContactPeriod.

        Measurement period end time (UTC)  # noqa: E501

        :return: The end_time of this SkinContactPeriod.
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: datetime):
        """Sets the end_time of this SkinContactPeriod.

        Measurement period end time (UTC)  # noqa: E501

        :param end_time: The end_time of this SkinContactPeriod.
        :type end_time: datetime
        """

        self._end_time = end_time

    @property
    def modified_time(self) -> datetime:
        """Gets the modified_time of this SkinContactPeriod.

        Measurement period modified time (UTC)  # noqa: E501

        :return: The modified_time of this SkinContactPeriod.
        :rtype: datetime
        """
        return self._modified_time

    @modified_time.setter
    def modified_time(self, modified_time: datetime):
        """Sets the modified_time of this SkinContactPeriod.

        Measurement period modified time (UTC)  # noqa: E501

        :param modified_time: The modified_time of this SkinContactPeriod.
        :type modified_time: datetime
        """

        self._modified_time = modified_time

    @property
    def skin_contact_changes(self) -> List[SkinContactChange]:
        """Gets the skin_contact_changes of this SkinContactPeriod.


        :return: The skin_contact_changes of this SkinContactPeriod.
        :rtype: List[SkinContactChange]
        """
        return self._skin_contact_changes

    @skin_contact_changes.setter
    def skin_contact_changes(self, skin_contact_changes: List[SkinContactChange]):
        """Sets the skin_contact_changes of this SkinContactPeriod.


        :param skin_contact_changes: The skin_contact_changes of this SkinContactPeriod.
        :type skin_contact_changes: List[SkinContactChange]
        """

        self._skin_contact_changes = skin_contact_changes
