# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TrainingLoadProLoadEnum(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    UNKNOWN = "UNKNOWN"
    VERY_LOW = "VERY_LOW"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
    NOT_AVAILABLE = "NOT_AVAILABLE"
    def __init__(self):  # noqa: E501
        """TrainingLoadProLoadEnum - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TrainingLoadProLoadEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The training-load-pro-load-enum of this TrainingLoadProLoadEnum.  # noqa: E501
        :rtype: TrainingLoadProLoadEnum
        """
        return util.deserialize_model(dikt, cls)
