# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TransactionLocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, transaction_id: int=None, resource_uri: str=None):  # noqa: E501
        """TransactionLocation - a model defined in Swagger

        :param transaction_id: The transaction_id of this TransactionLocation.  # noqa: E501
        :type transaction_id: int
        :param resource_uri: The resource_uri of this TransactionLocation.  # noqa: E501
        :type resource_uri: str
        """
        self.swagger_types = {
            'transaction_id': int,
            'resource_uri': str
        }

        self.attribute_map = {
            'transaction_id': 'transaction-id',
            'resource_uri': 'resource-uri'
        }
        self._transaction_id = transaction_id
        self._resource_uri = resource_uri

    @classmethod
    def from_dict(cls, dikt) -> 'TransactionLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transaction-location of this TransactionLocation.  # noqa: E501
        :rtype: TransactionLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transaction_id(self) -> int:
        """Gets the transaction_id of this TransactionLocation.

        Id of the created transaction  # noqa: E501

        :return: The transaction_id of this TransactionLocation.
        :rtype: int
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id: int):
        """Sets the transaction_id of this TransactionLocation.

        Id of the created transaction  # noqa: E501

        :param transaction_id: The transaction_id of this TransactionLocation.
        :type transaction_id: int
        """

        self._transaction_id = transaction_id

    @property
    def resource_uri(self) -> str:
        """Gets the resource_uri of this TransactionLocation.

        Absolute links to the created transaction  # noqa: E501

        :return: The resource_uri of this TransactionLocation.
        :rtype: str
        """
        return self._resource_uri

    @resource_uri.setter
    def resource_uri(self, resource_uri: str):
        """Sets the resource_uri of this TransactionLocation.

        Absolute links to the created transaction  # noqa: E501

        :param resource_uri: The resource_uri of this TransactionLocation.
        :type resource_uri: str
        """

        self._resource_uri = resource_uri
