# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserExtraInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, value: str=None, index: int=None, name: str=None):  # noqa: E501
        """UserExtraInfo - a model defined in Swagger

        :param value: The value of this UserExtraInfo.  # noqa: E501
        :type value: str
        :param index: The index of this UserExtraInfo.  # noqa: E501
        :type index: int
        :param name: The name of this UserExtraInfo.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'value': str,
            'index': int,
            'name': str
        }

        self.attribute_map = {
            'value': 'value',
            'index': 'index',
            'name': 'name'
        }
        self._value = value
        self._index = index
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'UserExtraInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserExtraInfo of this UserExtraInfo.  # noqa: E501
        :rtype: UserExtraInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> str:
        """Gets the value of this UserExtraInfo.

        Value provided by the customer  # noqa: E501

        :return: The value of this UserExtraInfo.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this UserExtraInfo.

        Value provided by the customer  # noqa: E501

        :param value: The value of this UserExtraInfo.
        :type value: str
        """

        self._value = value

    @property
    def index(self) -> int:
        """Gets the index of this UserExtraInfo.

        Item index  # noqa: E501

        :return: The index of this UserExtraInfo.
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index: int):
        """Sets the index of this UserExtraInfo.

        Item index  # noqa: E501

        :param index: The index of this UserExtraInfo.
        :type index: int
        """

        self._index = index

    @property
    def name(self) -> str:
        """Gets the name of this UserExtraInfo.

        Name of the extra info asked from customer  # noqa: E501

        :return: The name of this UserExtraInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UserExtraInfo.

        Name of the extra info asked from customer  # noqa: E501

        :param name: The name of this UserExtraInfo.
        :type name: str
        """

        self._name = name
