# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WebhookPayloadExercise(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, event: str=None, user_id: int=None, entity_id: str=None, timestamp: datetime=None, url: str=None):  # noqa: E501
        """WebhookPayloadExercise - a model defined in Swagger

        :param event: The event of this WebhookPayloadExercise.  # noqa: E501
        :type event: str
        :param user_id: The user_id of this WebhookPayloadExercise.  # noqa: E501
        :type user_id: int
        :param entity_id: The entity_id of this WebhookPayloadExercise.  # noqa: E501
        :type entity_id: str
        :param timestamp: The timestamp of this WebhookPayloadExercise.  # noqa: E501
        :type timestamp: datetime
        :param url: The url of this WebhookPayloadExercise.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'event': str,
            'user_id': int,
            'entity_id': str,
            'timestamp': datetime,
            'url': str
        }

        self.attribute_map = {
            'event': 'event',
            'user_id': 'user_id',
            'entity_id': 'entity_id',
            'timestamp': 'timestamp',
            'url': 'url'
        }
        self._event = event
        self._user_id = user_id
        self._entity_id = entity_id
        self._timestamp = timestamp
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'WebhookPayloadExercise':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The webhookPayloadExercise of this WebhookPayloadExercise.  # noqa: E501
        :rtype: WebhookPayloadExercise
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event(self) -> str:
        """Gets the event of this WebhookPayloadExercise.

        Type of available data.  # noqa: E501

        :return: The event of this WebhookPayloadExercise.
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event: str):
        """Sets the event of this WebhookPayloadExercise.

        Type of available data.  # noqa: E501

        :param event: The event of this WebhookPayloadExercise.
        :type event: str
        """

        self._event = event

    @property
    def user_id(self) -> int:
        """Gets the user_id of this WebhookPayloadExercise.

        Id of the user who has new data.  # noqa: E501

        :return: The user_id of this WebhookPayloadExercise.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this WebhookPayloadExercise.

        Id of the user who has new data.  # noqa: E501

        :param user_id: The user_id of this WebhookPayloadExercise.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def entity_id(self) -> str:
        """Gets the entity_id of this WebhookPayloadExercise.

        Id of the available data.  # noqa: E501

        :return: The entity_id of this WebhookPayloadExercise.
        :rtype: str
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id: str):
        """Sets the entity_id of this WebhookPayloadExercise.

        Id of the available data.  # noqa: E501

        :param entity_id: The entity_id of this WebhookPayloadExercise.
        :type entity_id: str
        """

        self._entity_id = entity_id

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this WebhookPayloadExercise.

        Time when webhook notification is sent.  # noqa: E501

        :return: The timestamp of this WebhookPayloadExercise.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this WebhookPayloadExercise.

        Time when webhook notification is sent.  # noqa: E501

        :param timestamp: The timestamp of this WebhookPayloadExercise.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def url(self) -> str:
        """Gets the url of this WebhookPayloadExercise.

        Url to the new available data.  # noqa: E501

        :return: The url of this WebhookPayloadExercise.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this WebhookPayloadExercise.

        Url to the new available data.  # noqa: E501

        :param url: The url of this WebhookPayloadExercise.
        :type url: str
        """

        self._url = url
