# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.webhook_type import WebhookType  # noqa: F401,E501
from swagger_server import util


class WebhookInfoData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, events: List[WebhookType]=None, url: str=None, active: bool=None):  # noqa: E501
        """WebhookInfoData - a model defined in Swagger

        :param id: The id of this WebhookInfoData.  # noqa: E501
        :type id: str
        :param events: The events of this WebhookInfoData.  # noqa: E501
        :type events: List[WebhookType]
        :param url: The url of this WebhookInfoData.  # noqa: E501
        :type url: str
        :param active: The active of this WebhookInfoData.  # noqa: E501
        :type active: bool
        """
        self.swagger_types = {
            'id': str,
            'events': List[WebhookType],
            'url': str,
            'active': bool
        }

        self.attribute_map = {
            'id': 'id',
            'events': 'events',
            'url': 'url',
            'active': 'active'
        }
        self._id = id
        self._events = events
        self._url = url
        self._active = active

    @classmethod
    def from_dict(cls, dikt) -> 'WebhookInfoData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The webhookInfo_data of this WebhookInfoData.  # noqa: E501
        :rtype: WebhookInfoData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this WebhookInfoData.

        Id of the webhook.  # noqa: E501

        :return: The id of this WebhookInfoData.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this WebhookInfoData.

        Id of the webhook.  # noqa: E501

        :param id: The id of this WebhookInfoData.
        :type id: str
        """

        self._id = id

    @property
    def events(self) -> List[WebhookType]:
        """Gets the events of this WebhookInfoData.

        Subscribed event types.  # noqa: E501

        :return: The events of this WebhookInfoData.
        :rtype: List[WebhookType]
        """
        return self._events

    @events.setter
    def events(self, events: List[WebhookType]):
        """Sets the events of this WebhookInfoData.

        Subscribed event types.  # noqa: E501

        :param events: The events of this WebhookInfoData.
        :type events: List[WebhookType]
        """

        self._events = events

    @property
    def url(self) -> str:
        """Gets the url of this WebhookInfoData.

        Url where the webhook notification is sent.  # noqa: E501

        :return: The url of this WebhookInfoData.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this WebhookInfoData.

        Url where the webhook notification is sent.  # noqa: E501

        :param url: The url of this WebhookInfoData.
        :type url: str
        """

        self._url = url

    @property
    def active(self) -> bool:
        """Gets the active of this WebhookInfoData.

        Is the webhook active.  # noqa: E501

        :return: The active of this WebhookInfoData.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this WebhookInfoData.

        Is the webhook active.  # noqa: E501

        :param active: The active of this WebhookInfoData.
        :type active: bool
        """

        self._active = active
