# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WebhookPayloadAlertness(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, event: str=None, user_id: int=None, _from: str=None, to: str=None, timestamp: datetime=None, url: str=None):  # noqa: E501
        """WebhookPayloadAlertness - a model defined in Swagger

        :param event: The event of this WebhookPayloadAlertness.  # noqa: E501
        :type event: str
        :param user_id: The user_id of this WebhookPayloadAlertness.  # noqa: E501
        :type user_id: int
        :param _from: The _from of this WebhookPayloadAlertness.  # noqa: E501
        :type _from: str
        :param to: The to of this WebhookPayloadAlertness.  # noqa: E501
        :type to: str
        :param timestamp: The timestamp of this WebhookPayloadAlertness.  # noqa: E501
        :type timestamp: datetime
        :param url: The url of this WebhookPayloadAlertness.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'event': str,
            'user_id': int,
            '_from': str,
            'to': str,
            'timestamp': datetime,
            'url': str
        }

        self.attribute_map = {
            'event': 'event',
            'user_id': 'user_id',
            '_from': 'from',
            'to': 'to',
            'timestamp': 'timestamp',
            'url': 'url'
        }
        self._event = event
        self._user_id = user_id
        self.__from = _from
        self._to = to
        self._timestamp = timestamp
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'WebhookPayloadAlertness':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The webhookPayloadAlertness of this WebhookPayloadAlertness.  # noqa: E501
        :rtype: WebhookPayloadAlertness
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event(self) -> str:
        """Gets the event of this WebhookPayloadAlertness.

        Type of available data.  # noqa: E501

        :return: The event of this WebhookPayloadAlertness.
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event: str):
        """Sets the event of this WebhookPayloadAlertness.

        Type of available data.  # noqa: E501

        :param event: The event of this WebhookPayloadAlertness.
        :type event: str
        """

        self._event = event

    @property
    def user_id(self) -> int:
        """Gets the user_id of this WebhookPayloadAlertness.

        Id of the user who has new data.  # noqa: E501

        :return: The user_id of this WebhookPayloadAlertness.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this WebhookPayloadAlertness.

        Id of the user who has new data.  # noqa: E501

        :param user_id: The user_id of this WebhookPayloadAlertness.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def _from(self) -> str:
        """Gets the _from of this WebhookPayloadAlertness.

        For consistency use period for all descriptions  # noqa: E501

        :return: The _from of this WebhookPayloadAlertness.
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from: str):
        """Sets the _from of this WebhookPayloadAlertness.

        For consistency use period for all descriptions  # noqa: E501

        :param _from: The _from of this WebhookPayloadAlertness.
        :type _from: str
        """

        self.__from = _from

    @property
    def to(self) -> str:
        """Gets the to of this WebhookPayloadAlertness.

        For consistency use period for all descriptions  # noqa: E501

        :return: The to of this WebhookPayloadAlertness.
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to: str):
        """Sets the to of this WebhookPayloadAlertness.

        For consistency use period for all descriptions  # noqa: E501

        :param to: The to of this WebhookPayloadAlertness.
        :type to: str
        """

        self._to = to

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this WebhookPayloadAlertness.

        Time when webhook notification is sent.  # noqa: E501

        :return: The timestamp of this WebhookPayloadAlertness.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this WebhookPayloadAlertness.

        Time when webhook notification is sent.  # noqa: E501

        :param timestamp: The timestamp of this WebhookPayloadAlertness.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def url(self) -> str:
        """Gets the url of this WebhookPayloadAlertness.

        Url to the new available data.  # noqa: E501

        :return: The url of this WebhookPayloadAlertness.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this WebhookPayloadAlertness.

        Url to the new available data.  # noqa: E501

        :param url: The url of this WebhookPayloadAlertness.
        :type url: str
        """

        self._url = url
