# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.zone import Zone  # noqa: F401,E501
from swagger_server import util


class Zones(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, zone: List[Zone]=None):  # noqa: E501
        """Zones - a model defined in Swagger

        :param zone: The zone of this Zones.  # noqa: E501
        :type zone: List[Zone]
        """
        self.swagger_types = {
            'zone': List[Zone]
        }

        self.attribute_map = {
            'zone': 'zone'
        }
        self._zone = zone

    @classmethod
    def from_dict(cls, dikt) -> 'Zones':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The zones of this Zones.  # noqa: E501
        :rtype: Zones
        """
        return util.deserialize_model(dikt, cls)

    @property
    def zone(self) -> List[Zone]:
        """Gets the zone of this Zones.

        List of heart rate zones.  # noqa: E501

        :return: The zone of this Zones.
        :rtype: List[Zone]
        """
        return self._zone

    @zone.setter
    def zone(self, zone: List[Zone]):
        """Sets the zone of this Zones.

        List of heart rate zones.  # noqa: E501

        :param zone: The zone of this Zones.
        :type zone: List[Zone]
        """

        self._zone = zone
